keys:
    - &nixos-mini-pc age1nr5k2ysvsqxdus6lcrcwjcx9xzjq45j4ec3xuq6tkqggjt4z998q57fmen
creation_rules:
    - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
      key_groups:
          - age:
                - *nixos-mini-pc
