#!/usr/bin/env zsh

# Start Yakuake
yakuake &
sleep 2

# Configure initial state of Yakuake
function instruct {
    cmd="qdbus org.kde.yakuake $1"
    eval $cmd &> /dev/null
    sleep 0.5
}

instruct "/yakuake/tabs setTabTitle 0 'NixOS'"
instruct "/yakuake/sessions runCommandInTerminal 0 'cd ~/Development/Git.Repositories/nixos'"
instruct "/yakuake/sessions runCommandInTerminal 0 'clear'"
instruct "/yakuake/sessions raiseSession 0"

# Start pCloud
pcloud &
sleep 2
