#!/usr/bin/env zsh

# Start Yakuake
yakuake &
sleep 2

# Configure initial state of Yakuake
function instruct {
    cmd="qdbus org.kde.yakuake $1"
    eval $cmd &> /dev/null
    sleep 0.5
}

instruct "/yakuake/tabs setTabTitle 0 'NixOS'"
instruct "/yakuake/sessions addSession"
instruct "/yakuake/tabs setTabTitle 1 'Init'"

# Sets session zero as the active session
instruct "/yakuake/sessions raiseSession 0"

# Preps the terminal for use
instruct "/yakuake/sessions runCommandInTerminal 0 'tmux'"
instruct "/yakuake/sessions runCommandInTerminal 0 'cd ~/Development/Git.Repositories/nixos'"
instruct "/yakuake/sessions runCommandInTerminal 0 'clear'"

# Updates the system on startup
instruct "/yakuake/sessions runCommandInTerminal 1 'cd ~/Development/Git.Repositories/nixos'"
instruct "/yakuake/sessions runCommandInTerminal 1 'git pull'"
instruct "/yakuake/sessions runCommandInTerminal 1 'sudo nixos-rebuild switch --flake .'" # Need to pass password to sudo command
instruct "/yakuake/sessions removeSession 1"
