#!/usr/bin/env zsh

currentDirectory=$(pwd)

mkdir -p /tmp/Git.Repositories
cd /tmp/Git.Repositories
git pull || git clone "git@github.com:Jamie050401/nixos.git"

sudo nixos-rebuild switch --flake .

cd $currentDirectory
