#!/usr/bin/env zsh

# Handles parameters passed into the script
while [[ "$#" -gt 0 ]]
do case $1 in
    -h|--hostName) hostName=$2
    shift;;
    *) echo "Unknown parameter: $1"
    shift;; 
esac
shift
done

sudo nixos-rebuild test --flake .#$hostName
