#!/usr/bin/env zsh

# Handles parameters passed into the script
directory="/tmp/Git.Repositories"
while [[ "$#" -gt 0 ]]
do case $1 in
    -h|--hostName) hostName=$2
    shift;;
    *) echo "Unknown parameter: $1"
    shift;; 
esac
shift
done

currentDirectory=$(pwd)
mkdir -p $directory
git -C pull $directory || git clone "git@github.com:Jamie050401/nixos.git" $directory
sudo nixos-rebuild switch --flake .#$hostName
cd $currentDirectory
