name: NixOS Update CI

on:
    schedule:
        - cron: '0 0 * * 0'
    workflow_dispatch:

jobs:
    Update:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  ref: "main"
                  fetch-depth: 0
            - name: Install Nix
              uses: cachix/install-nix-action@v22
              with:
                  nix_path: nixpkgs=channel:nixos-23.11
            - name: Build and Update
              run: |
                  nix flake check
                  nix build --profile /nix/var/nix/profiles/system .
                  nix flake update
            #- name: Commit and Push
            #  uses: actions-js/push@master
            #  with:
            #      github_token: ${{ secrets.TOKEN }}
            #      author_name: "github-actions"
            #      message: "Updated NixOS"
            #      branch: "main"
            #      empty: false
