name: NixOS Update

on:
    schedule:
        - cron: '0 0 * * 0'
    workflow_dispatch:

env:
    HOST_NAME: nixos-mini-pc

jobs:
    Update:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  ref: "main"
                  fetch-depth: 0
            - name: Install Nix
              uses: cachix/install-nix-action@v25
              with:
                  nix_path: nixpkgs=channel:nixos-23.11
            - name: Update NixOS
              run: |
                  nix-channel --update
                  nix build .#nixosConfigurations.$HOST_NAME.config.system.build.toplevel
                  nix flake update
            - name: Create PR
              id: create-pr
              uses: peter-evans/create-pull-request@v5
              with:
                  base: main
                  branch: update
                  delete-branch: true
                  token: ${{ secrets.TOKEN }}
                  committer: "GitHub Actions <actions@no-reply.github.com>"
                  commit-message: "Updated NixOS"
                  title: "Update NixOS"
                  body: "Automated update of NixOS"
                  labels: automated
