name: NixOS Update

on:
    schedule:
        - cron: '0 0 * * 0'
    workflow_dispatch:

jobs:
    Update:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  ref: "main"
                  fetch-depth: 0
            - name: Install Nix
              uses: cachix/install-nix-action@v25
              with:
                  nix_path: nixpkgs=channel:nixos-23.11
            - name: Update NixOS
              run: nix flake update
            - name: Create PR
              id: create-pr
              uses: peter-evans/create-pull-request@v5
              with:
                  base: main
                  branch: update
                  delete-branch: true
                  token: ${{ secrets.TOKEN }}
                  committer: GitHub Actions <actions@no-reply.github.com>
                  commit-message: "Updated flake.lock"
                  title: "Update flake.lock"
                  body: "Automated update of flake.lock"
                  labels: automated
