name: NixOS Update

on:
    schedule:
        - cron: '0 0 * * 0'
    workflow_dispatch:

env:
    HOST_NAME: nixos-mini-pc

jobs:
    Update:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  ref: "main"
                  fetch-depth: 0
            - name: Install Nix
              uses: cachix/install-nix-action@v25
              with:
                  nix_path: nixpkgs=channel:nixos-23.11
            - name: Update flake.lock
              uses: DeterminateSystems/update-flake-lock@main
              with:
                  pr-title: "Update flake.lock"
                  pr-labels: |
                    dependencies
                    automated
            - name: Update NixOS
              run: |
                  nix channel --update
                  nix build .#nixosConfigurations.$HOST_NAME.config.system.build.toplevel
            - name: Create PR
              id: create-pr
              uses: peter-evans/create-pull-request@v5
              with:
                  base: main
                  branch: update
                  delete-branch: true
                  token: ${{ secrets.TOKEN }}
                  title: "Update NixOS"
